sqlite:
  db_path: 'project_data.db'

input_path: 'template.xlsx'           # 输入的 XLSX 模板文件路径
output_path: 'output.xlsx'            # 输出的 XLSX 文件路径

mapping:
  project_column: 'B'                 # 维度所在的列
  column_num: 2                       # 维度所在的列号
  project_id_column: 'project_id'     # 数据表中的维度字段
  start_row: 5                        # 开始写入的行
  indicator_row: 4                    # 指标所在的行

project_mapping:
  '项目A': 1
  '项目B': 2
  '项目C': 3
  '项目D': 4

indicator_mapping:
  '个数': 'count'
  '规模': 'scale'
  '个数占比': 'count_ratio'

excel_style:
  font:
    name: '微软雅黑'   # 字体名称
    size: 12          # 字体大小
    bold: False       # 是否加粗
    italic: False     # 是否斜体
    color: '000000'   # 字体颜色
  fill:
    start_color: 'FFFFFF'   # 白色背景
  alignment:
    horizontal: 'center'    # 对齐方式 center left right
    vertical: 'center'

#formatting_targets:
#  "10":  # 对第10行应用格式
#    font:
#      name: 'Arial'
#      size: 12
#      bold: True
#      italic: False
#      color: '000000'  # 黑色字体
#    fill:
#      start_color: 'FFFFFF'  # 白色背景
#      end_color: 'FFFFFF'
#      fill_type: 'solid'
#    alignment:
#      horizontal: 'center'
#      vertical: 'center'
#
#  "D":  # 对D列应用格式
#    font:
#      name: 'Times New Roman'
#      size: 10
#      bold: True
#      italic: False
#      color: '0000FF'  # 蓝色字体
#    fill:
#      start_color: 'FFFFFF'
#      end_color: 'FFFFFF'
#      fill_type: 'solid'
#    alignment:
#      horizontal: 'right'
#      vertical: 'center'
#
#  "F":  # 对E列应用格式
#    font:
#      name: 'Times New Roman'
#      size: 10
#      bold: True
#      italic: False
#      color: '0000FF'  # 蓝色字体
#    fill:
#      start_color: 'FFFFFF'
#      end_color: 'FFFFFF'
#      fill_type: 'solid'
#    alignment:
#      horizontal: 'right'
#      vertical: 'center'
#
#  "A1":  # 对特定单元格A1应用格式
#    font:
#      name: 'Arial'
#      size: 14
#      bold: True
#      italic: False
#      color: '008000'  # 绿色字体
#    fill:
#      start_color: '00FF00'  # 绿色背景
#      end_color: '00FF00'
#      fill_type: 'solid'
#    alignment:
#      horizontal: 'center'
#      vertical: 'center'
#
#  "D10": # 对特定单元格A1应用格式
#    font:
#      name: 'Arial'
#      size: 14
#      bold: True
#      italic: False
#      color: '008000'  # 绿色字体
#    fill:
#      start_color: '00FF00'  # 绿色背景
#      end_color: '00FF00'
#      fill_type: 'solid'
#    alignment:
#      horizontal: 'center'
#      vertical: 'center'
