sqlite:
  db_path: 'new_project_data.db'

input_path: './data/input_file1.xlsx'           # 输入的 XLSX 模板文件路径
output_path: 'output.xlsx'            # 输出的 XLSX 文件路径

start_column: 3                      # 维度所在的列号
start_row: 5                        # 开始写入的行

query: '
    SELECT
        prod_qty,
        prod_pct,
        prod_wow_change,
        prod_wow_ratio,
        prod_yoy_change,
        prod_yoy_ratio,
        prod_1st_quartile,
        prod_2nd_quartile,
        prod_3rd_quartile,
        prod_top5_tot,
        prod_top5_pct,
        payin_trust_scale_100m,
        trust_scale_pct,
        scale_wow_change,
        scale_wow_ratio,
        scale_yoy_change,
        scale_yoy_ratio,
        scale_1st_quartile,
        scale_2nd_quartile,
        scale_3rd_quartile,
        scale_top5_tot,
        scale_top5_pct,
        issuing_org_qty,
        issuing_org_wow_change,
        issuing_org_wow_ratio
    FROM reg_init_indus_sum_wk 
    ORDER BY order_idx;
    '



#project_mapping:
#  '项目A': 1
#  '项目B': 2
#  '项目C': 3
#  '项目D': 4
#
#indicator_mapping:
#  '个数': 'count'
#  '规模': 'scale'
#  '个数占比': 'count_ratio'

#excel_style:
#  font:
#    name: '微软雅黑'   # 字体名称
#    size: 12          # 字体大小
#    bold: False       # 是否加粗
#    italic: False     # 是否斜体
#    color: '000000'   # 字体颜色
#  fill:
#    start_color: 'FFFFFF'   # 白色背景
#  alignment:
#    horizontal: 'center'    # 对齐方式 center left right
#    vertical: 'center'

#formatting_targets:
#  "10":  # 对第10行应用格式
#    font:
#      name: 'Arial'
#      size: 12
#      bold: True
#      italic: False
#      color: '000000'  # 黑色字体
#    fill:
#      start_color: 'FFFFFF'  # 白色背景
#      end_color: 'FFFFFF'
#      fill_type: 'solid'
#    alignment:
#      horizontal: 'center'
#      vertical: 'center'
#
#  "D":  # 对D列应用格式
#    font:
#      name: 'Times New Roman'
#      size: 10
#      bold: True
#      italic: False
#      color: '0000FF'  # 蓝色字体
#    fill:
#      start_color: 'FFFFFF'
#      end_color: 'FFFFFF'
#      fill_type: 'solid'
#    alignment:
#      horizontal: 'right'
#      vertical: 'center'
#
#  "F":  # 对E列应用格式
#    font:
#      name: 'Times New Roman'
#      size: 10
#      bold: True
#      italic: False
#      color: '0000FF'  # 蓝色字体
#    fill:
#      start_color: 'FFFFFF'
#      end_color: 'FFFFFF'
#      fill_type: 'solid'
#    alignment:
#      horizontal: 'right'
#      vertical: 'center'
#
#  "A1":  # 对特定单元格A1应用格式
#    font:
#      name: 'Arial'
#      size: 14
#      bold: True
#      italic: False
#      color: '008000'  # 绿色字体
#    fill:
#      start_color: '00FF00'  # 绿色背景
#      end_color: '00FF00'
#      fill_type: 'solid'
#    alignment:
#      horizontal: 'center'
#      vertical: 'center'
#
#  "D10": # 对特定单元格A1应用格式
#    font:
#      name: 'Arial'
#      size: 14
#      bold: True
#      italic: False
#      color: '008000'  # 绿色字体
#    fill:
#      start_color: '00FF00'  # 绿色背景
#      end_color: '00FF00'
#      fill_type: 'solid'
#    alignment:
#      horizontal: 'center'
#      vertical: 'center'
