sqlite:
  db_path: 'project_data.db'  # SQLite数据库文件路径

mapping:
  project_column: 'B'  # Excel中项目名称的列
  project_id_column: 'project_id'  # 数据库表中的项目ID字段
  start_row: 5  # 数据从Excel中的哪一行开始
  indicator_row: 4  # 指标字段在Excel中的行号

# 项目名称与项目ID的对应关系（Excel中的项目名称: 数据库中的项目ID）
project_mapping:
  '项目A': 1
  '项目B': 2
  '项目C': 3
  '项目D': 4

# Excel指标名称与数据库表中字段名称的对应关系
indicator_mapping:
  '个数': 'count'
  '规模': 'scale'
  '个数占比': 'count_ratio'


#  columns:                                  # 应用范围： all,columns,rows,cells     全部，指定列，指定行，指定单元格。  可以一直王下面添加formatting:
#    B:
#      font:                                 # 字体
#        name: 'Arial'
#        size: 12
#        color: '000000'  # 黑色
#      fill:                                  # 背景
#        color: 'FFFFFF'  # 白色背景
#      alignment:                             # 对齐方式
#        horizontal: 'center'
#        vertical: 'center'
#      column_width: 15                       # 列款

formatting:
  all:
    font:
      name: 'Arial'
      size: 12
      color: '000000'  # 黑色
    fill:
      color: 'FFFFFF'  # 白色背景
    alignment:
      horizontal: 'center'
      vertical: 'center'
    column_width: 15

#  columns:
#    B:
#      font:
#        name: 'Arial'
#        size: 12
#        color: '000000'  # 黑色
#      fill:
#        color: 'FFFFFF'  # 白色背景
#      alignment:
#        horizontal: 'center'
#        vertical: 'center'
#      column_width: 15
#
#  rows:
#    2:
#      font:
#        name: 'Arial'
#        size: 12
#        color: '000000'  # 黑色
#      fill:
#        color: 'FFFFFF'  # 白色背景
#      alignment:
#        horizontal: 'center'
#        vertical: 'center'
#      column_width: 15
#
#  cells:
#    A5:
#      font:
#        name: 'Arial'
#        size: 12
#        color: '0000FF'  # 蓝色
#      fill:
#        color: 'E0E0E0'  # 浅灰色背景
#      alignment:
#        horizontal: 'center'
#        vertical: 'center'
#    B8:
#      font:
#        name: 'Times New Roman'
#        size: 12
#        color: 'FF00FF'  # 紫色
#      fill:
#        color: 'FFFFF0'  # 米色背景
#      alignment:
#        horizontal: 'left'
#        vertical: 'center'